### ISSUE TITLE
Can you update the code in swift 2.0??

### ISSUE THREAD

**Issue by htarwara6245** [hoffmanjon/SQLiteDataAccessLayer#1]
I am beginner to swift as well as working with CoreData.So,can you please update the code in swift 2.0?

**Comment by hoffmanjon** [comment]
I have a swift 2.0 project here:  https://github.com/hoffmanjon/SQLiteDataAccessLayer2
You can read the blog post that explains the code here:  http://masteringswift.blogspot.com/2015/09/create-data-access-layer-with.html
